name: genelab-validate-raw-2025-04-17
channels:
  - conda-forge
  - bioconda
  - nodefault
dependencies:
  - python=3.10
  - pandas=2.2.3
  - fastqc=0.12.1
  - multiqc=1.28
  - fastq_utils=0.25.2
  - coreutils=9.5
  - gzip=1.14
  - zip=3.0 
  - nextflow=24.10.5